[package]
name = "simpalt-tmux"
edition.workspace = true
version.workspace = true

[dependencies]
simpalt.path = "../simpalt"
chrono.workspace = true

[dev-dependencies]
regex.workspace = true

[features]
default = ["media"]
media = ["dep:unicode-segmentation", "dep:media-remote", "dep:mpris"]

[target.'cfg(target_os = "linux")'.dependencies]
mpris = { workspace = true, optional = true }
unicode-segmentation = { workspace = true, optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
media-remote = { workspace = true, optional = true }
unicode-segmentation = { workspace = true, optional = true }
